"""empty message

Revision ID: 227e738bc1b5
Revises: ab3acb029e4d
Create Date: 2023-01-11 10:22:53.487232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227e738bc1b5'
down_revision = 'ab3acb029e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###